### ISSUE TITLE
Library linking broken in 5.3.4 for macOS and Linux

### ISSUE THREAD

**Issue by rrgeorge** [nut-tree/opencv4nodejs#12]
Same script works fine with 5.3.3, but fails symbol lookup on 5.3.4 on macOS and Linux. It does work on Windows.
With macOS 10.15.7:
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionEhhh  Referenced from: /Users/rgeorge/ddblog/ddblog/node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionEhhh  Referenced from: /Users/rgeorge/ddblog/ddblog/node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs.node
  Expected in: flat namespace

/Users/rgeorge/ddblog/ddblog/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGABRT
```
With debian Linux (amd64):
```
/home/rgeorge/encounterlog/node_modules/electron/dist/electron testgrid.js: symbol lookup error: /home/rgeorge/encounterlog/node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionEhhh
```
